builds:
  - id: "particard"
    main: ./cmd/partycard/main.go
    binary: particard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: particard-archive
    builds: ["particard"]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
# - `release`: for GitHub/GitLab releases
# - `brews`: for Homebrew taps
# - `scoop`: for Scoop manifests
# - `docker_images`: for Docker image builds
